<?php
$countries = [
    "AFGHANISTAN",
    "AFRIQUE DU SUD",
    "ALBANIE",
    "ALGERIE",
    "ALLEMAGNE",
    "ANDORRE",
    "ANGOLA",
    "ANGUILLA",
    "ANTARCTIQUE",
    "ANTIGUA BARBUDA",
    "ANTILLES NEERLANDAIS",
    "ARABIESAOUDITE",
    "ARGENTINE",
    "ARMENIE",
    "ARUBA",
    "AUSTRALIE",
    "AUTHO. PALESTINIENNE",
    "AUTRICHE",
    "AZERBAIDJAN",
    "BAHAMAS",
    "BAHREIN",
    "BANGLADESH",
    "BARBADE",
    "BELARUS",
    "BELGIQUE",
    "BELIZE",
    "BENIN",
    "BERMUDES",
    "BHOUTAN",
    "BOLIVIE",
    "BOSNIE-HERZEGOVINE",
    "BOTSWANA",
    "BRESIL",
    "BRUNEI",
    "BULGARIE",
    "BURKINA FASO",
    "BURUNDI",
    "CAMBODGE",
    "CAMEROUN",
    "CANADA",
    "CAP VERT",
    "CHILI",
    "CHINE",
    "CHYPRE",
    "COLOMBIE",
    "COMORES",
    "CONGO",
    "COREE DU NORD",
    "COREE DU SUD",
    "COSTA RICA",
    "COTE D'IVOIRE",
    "CROATIE",
    "CUBA",
    "DANEMARK",
    "DJIBOUTI",
    "DOMINIQUE",
    "EGYPTE",
    "EL SALVADOR",
    "EMIRAT ARABE UNIS",
    "EQUATEUR",
    "ERYTHREE",
    "ESPAGNE",
    "ESTONIE",
    "ETHIOPIE",
    "FALKLAND",
    "FIDJI",
    "FINLANDE",
    "FRANCE",
    "GABON",
    "GAMBIE",
    "GEORGIE",
    "GEORGIE DU SUD",
    "GHANA",
    "GIBRALTAR",
    "GRECE",
    "GRENADE",
    "GROELAND",
    "GUADELOUPE",
    "GUAM",
    "GUATEMALA",
    "GUINEE",
    "GUINEE BISSAU",
    "GUINEE EQUATORIALE",
    "GUYANA",
    "GUYANE FRANCAISE",
    "HAITI",
    "HEARD &amp; MAC DONALD",
    "HONDURAS",
    "HONG KONG",
    "HONGRIE",
    "ILE BOUVET",
    "ILE CHRISTMAS",
    "ILE NORFOLK",
    "ILES CAYMAN",
    "ILES COCOS (KEELING)",
    "ILES COOK",
    "ILES FEROE",
    "ILES MARSHALL",
    "ILES TOKELAU",
    "ILES US DU PACIFIQUE",
    "ILES VIERGES AMERIC.",
    "ILES VIERGES BRITAN.",
    "INDE",
    "INDONESIE",
    "IRAK",
    "IRAN",
    "IRLANDE",
    "ISLANDE",
    "ISRAEL",
    "ITALIE",
    "JAMAIQUE",
    "JAPON",
    "JORDANIE",
    "KAZAKHSTAN",
    "KENYA",
    "KIRGHISTAN",
    "KIRIBATI",
    "KOWEIT",
    "LAOS",
    "LESOTHO",
    "LETTONIE",
    "LIBAN",
    "LIBERIA",
    "LIBYE",
    "LIECHTENSTEIN",
    "LITUANIE",
    "LUXEMBOURG",
    "MACAO",
    "MACEDOINE",
    "MADAGASCAR",
    "MALAWI",
    "MALAYSIA",
    "MALDIVES",
    "MALI",
    "MALTE",
    "MARIANES DU NORD",
    "MAROC",
    "MARTINIQUE",
    "MAURICE",
    "MAURITANIE",
    "MAYOTTE",
    "MEXIQUE",
    "MICRONESIE",
    "MOLDAVIE",
    "MONACO",
    "MONGOLIE",
    "MONTSERRAT",
    "MOZAMBIQUE",
    "MYANMAR",
    "NAMIBIE",
    "NAURU",
    ">Néant",
    "NEPAL",
    "NICARAGUA",
    "NIGER",
    "NIGERIA",
    "NIUE",
    "NORVEGE",
    "NOUVELLE CALEDONIE",
    "NOUVELLE ZELANDE",
    "OMAN",
    "OUGANDA",
    "OUZBEKISTAN",
    "PAKISTAN",
    "PALAU",
    "PANAMA",
    "PAPOUASIE NLE GUINEE",
    "PARAGUAY",
    "PAYS BAS",
    "PAYS ETRANGER",
    "PEROU",
    "PHILIPPINES",
    "PITCAIRN",
    "POLOGNE",
    "POLYNESIE FRANCAISE",
    "PORTO RICO",
    "PORTUGAL",
    "QATAR",
    "R. D. CONGO",
    "REP. CENTRAFRICAINE",
    "REP. DOMINICAINE",
    "REP. TCHEQUE",
    "REUNION",
    "ROUMANIE",
    "ROYAUME UNI",
    "RUSSIE",
    "RWANDA",
    "SAHARA OCCIDENTAL",
    "SAINT MARIN",
    "SAINTE HELENE",
    "SALOMON",
    "SAMOA",
    "SAMOA AMERICAINES",
    "SAO TOME &amp; PRINCIPE",
    "SENEGAL",
    "SEYCHELLES",
    "SIERRA LEONE",
    "SINGAPOUR",
    "SLOVAQUIE",
    "SLOVENIE",
    "SOMALIE",
    "SOUDAN",
    "SRI-LANKA",
    "ST KITTS",
    "ST VINCENT",
    "ST-PIERRE &amp; MIQUELON",
    "STE LUCIE",
    "SUEDE",
    "SUISSE",
    "SURINAM",
    "SVALBARD JAN MAYEN",
    "SWAZILAND",
    "SYRIE",
    "T.A.A.F",
    "TADJIKISTAN",
    "TAIWAN",
    "TANZANIE",
    "TCHAD",
    "TERR. BRIT. OC. INDIEN",
    "THAILANDE",
    "TIMOR ORIENTAL",
    "TOGO",
    "TONGA",
    "TRINIDAD &amp; TOBAGO",
    "TUNISIE",
    "TURK &amp; CAIQUES",
    "TURKMENISTAN",
    "TURQUIE",
    "TUVALU",
    "UKRAINE",
    "UNION EUROPEENNE",
    "URUGUAY",
    "USA",
    "VANUATU",
    "VATICAN",
    "VENEZUELA",
    "VIETNAM",
    "WALLIS &amp; FUTUNA",
    "YEMEN",
    "YOUGOSLAVIE",
    "ZAMBIE",
    "ZIMBABWE",
    "ZONE NEUTRE IRK/SAU"

];