version: '3.9'

networks:
  glab:
    name: glab

volumes:
  data:


services:
  web:
    image: thecodingmachine/php:8.2-v4-apache-node16
    depends_on:
      - mysql
    environment:
        APACHE_DOCUMENT_ROOT: "public/"
        PHP_EXTENSIONS: "apcu mysqli pdo_mysql intl gd xdebug zip bcmath"
    volumes:
      - ./:/var/www/html:rw
    ports:
      - "5173:5173"
    labels:
      - traefik.enable=true
      - traefik.http.routers.web_router.rule=Host(`${HOST_URL}`)
      - traefik.http.routers.web_router.entrypoints=web
      - traefik.http.routers.web_router.service=web_service
      - traefik.http.services.web_service.loadbalancer.server.port=80
      - traefik.http.routers.vite_router.rule=Host(`${HOST_URL}`)
      - traefik.http.routers.vite_router.entrypoints=vite
      - traefik.http.routers.vite_router.service=vite_service
      - traefik.http.services.vite_service.loadbalancer.server.port=5173
    networks:
      - glab

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - data:/var/lib/mysql
    networks:
      - glab

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: always
    depends_on:
      - mysql
    environment:
      UPLOAD_LIMIT: 300M
    links:
      - mysql:db
    labels:
      - traefik.enable=true
      - traefik.http.routers.pma_router.rule=Host(`pma.${HOST_URL}`)
    networks:
      - glab

  mailhog:
    image: mailhog/mailhog
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailhog_router.rule=Host(`mail.${HOST_URL}`)
      - traefik.http.routers.mailhog_router.entrypoints=mailhog
      - traefik.http.routers.mailhog_router.service=mailhog_service
      - traefik.http.services.mailhog_service.loadbalancer.server.port=8025
    networks:
      - glab

  traefik:
    image: traefik:v3.0
    restart: unless-stopped
    depends_on:
      - web
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=glab
      - --api.dashboard=true
      - --api.insecure=true
      - --entryPoints.web.address=:80
      - --entryPoints.vite.address=:5173
      - --entryPoints.mailhog.address=:8025
    ports:
      - "80:80"
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik_dashboard_router.rule=Host(`traefik.$HOST_URL`)
      - traefik.http.routers.traefik_dashboard_router.entrypoints=web
      - traefik.http.routers.traefik_dashboard_router.service=traefik_dashboard_service
      - traefik.http.services.traefik_dashboard_service.loadbalancer.server.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - glab