@php
    $countries = [
        'AFGHANISTAN',
        'AFRIQUE DU SUD',
        'ALBANIE',
        'ALGERIE',
        'ALLEMAGNE',
        'ANDORRE',
        'ANGOLA',
        'ANGUILLA',
        'ANTARCTIQUE',
        'ANTIGUA BARBUDA',
        'ANTILLES NEERLANDAIS',
        'ARABIESAOUDITE',
        'ARGENTINE',
        'ARMENIE',
        'ARUBA',
        'AUSTRALIE',
        'AUTHO. PALESTINIENNE',
        'AUTRICHE',
        'AZERBAIDJAN',
        'BAHAMAS',
        'BAHREIN',
        'BANGLADESH',
        'BARBADE',
        'BELARUS',
        'BELGIQUE',
        'BELIZE',
        'BENIN',
        'BERMUDES',
        'BHOUTAN',
        'BOLIVIE',
        'BOSNIE-HERZEGOVINE',
        'BOTSWANA',
        'BRESIL',
        'BRUNEI',
        'BULGARIE',
        'BURKINA FASO',
        'BURUNDI',
        'CAMBODGE',
        'CAMEROUN',
        'CANADA',
        'CAP VERT',
        'CHILI',
        'CHINE',
        'CHYPRE',
        'COLOMBIE',
        'COMORES',
        'CONGO',
        'COREE DU NORD',
        'COREE DU SUD',
        'COSTA RICA',
        "COTE D'IVOIRE",
        'CROATIE',
        'CUBA',
        'DANEMARK',
        'DJIBOUTI',
        'DOMINIQUE',
        'EGYPTE',
        'EL SALVADOR',
        'EMIRAT ARABE UNIS',
        'EQUATEUR',
        'ERYTHREE',
        'ESPAGNE',
        'ESTONIE',
        'ETHIOPIE',
        'FALKLAND',
        'FIDJI',
        'FINLANDE',
        'FRANCE',
        'GABON',
        'GAMBIE',
        'GEORGIE',
        'GEORGIE DU SUD',
        'GHANA',
        'GIBRALTAR',
        'GRECE',
        'GRENADE',
        'GROELAND',
        'GUADELOUPE',
        'GUAM',
        'GUATEMALA',
        'GUINEE',
        'GUINEE BISSAU',
        'GUINEE EQUATORIALE',
        'GUYANA',
        'GUYANE FRANCAISE',
        'HAITI',
        'HEARD &amp; MAC DONALD',
        'HONDURAS',
        'HONG KONG',
        'HONGRIE',
        'ILE BOUVET',
        'ILE CHRISTMAS',
        'ILE NORFOLK',
        'ILES CAYMAN',
        'ILES COCOS (KEELING)',
        'ILES COOK',
        'ILES FEROE',
        'ILES MARSHALL',
        'ILES TOKELAU',
        'ILES US DU PACIFIQUE',
        'ILES VIERGES AMERIC.',
        'ILES VIERGES BRITAN.',
        'INDE',
        'INDONESIE',
        'IRAK',
        'IRAN',
        'IRLANDE',
        'ISLANDE',
        'ISRAEL',
        'ITALIE',
        'JAMAIQUE',
        'JAPON',
        'JORDANIE',
        'KAZAKHSTAN',
        'KENYA',
        'KIRGHISTAN',
        'KIRIBATI',
        'KOWEIT',
        'LAOS',
        'LESOTHO',
        'LETTONIE',
        'LIBAN',
        'LIBERIA',
        'LIBYE',
        'LIECHTENSTEIN',
        'LITUANIE',
        'LUXEMBOURG',
        'MACAO',
        'MACEDOINE',
        'MADAGASCAR',
        'MALAWI',
        'MALAYSIA',
        'MALDIVES',
        'MALI',
        'MALTE',
        'MARIANES DU NORD',
        'MAROC',
        'MARTINIQUE',
        'MAURICE',
        'MAURITANIE',
        'MAYOTTE',
        'MEXIQUE',
        'MICRONESIE',
        'MOLDAVIE',
        'MONACO',
        'MONGOLIE',
        'MONTSERRAT',
        'MOZAMBIQUE',
        'MYANMAR',
        'NAMIBIE',
        'NAURU',
        '>Néant',
        'NEPAL',
        'NICARAGUA',
        'NIGER',
        'NIGERIA',
        'NIUE',
        'NORVEGE',
        'NOUVELLE CALEDONIE',
        'NOUVELLE ZELANDE',
        'OMAN',
        'OUGANDA',
        'OUZBEKISTAN',
        'PAKISTAN',
        'PALAU',
        'PANAMA',
        'PAPOUASIE NLE GUINEE',
        'PARAGUAY',
        'PAYS BAS',
        'PAYS ETRANGER',
        'PEROU',
        'PHILIPPINES',
        'PITCAIRN',
        'POLOGNE',
        'POLYNESIE FRANCAISE',
        'PORTO RICO',
        'PORTUGAL',
        'QATAR',
        'R. D. CONGO',
        'REP. CENTRAFRICAINE',
        'REP. DOMINICAINE',
        'REP. TCHEQUE',
        'REUNION',
        'ROUMANIE',
        'ROYAUME UNI',
        'RUSSIE',
        'RWANDA',
        'SAHARA OCCIDENTAL',
        'SAINT MARIN',
        'SAINTE HELENE',
        'SALOMON',
        'SAMOA',
        'SAMOA AMERICAINES',
        'SAO TOME &amp; PRINCIPE',
        'SENEGAL',
        'SEYCHELLES',
        'SIERRA LEONE',
        'SINGAPOUR',
        'SLOVAQUIE',
        'SLOVENIE',
        'SOMALIE',
        'SOUDAN',
        'SRI-LANKA',
        'ST KITTS',
        'ST VINCENT',
        'ST-PIERRE &amp; MIQUELON',
        'STE LUCIE',
        'SUEDE',
        'SUISSE',
        'SURINAM',
        'SVALBARD JAN MAYEN',
        'SWAZILAND',
        'SYRIE',
        'T.A.A.F',
        'TADJIKISTAN',
        'TAIWAN',
        'TANZANIE',
        'TCHAD',
        'TERR. BRIT. OC. INDIEN',
        'THAILANDE',
        'TIMOR ORIENTAL',
        'TOGO',
        'TONGA',
        'TRINIDAD &amp; TOBAGO',
        'TUNISIE',
        'TURK &amp; CAIQUES',
        'TURKMENISTAN',
        'TURQUIE',
        'TUVALU',
        'UKRAINE',
        'UNION EUROPEENNE',
        'URUGUAY',
        'USA',
        'VANUATU',
        'VATICAN',
        'VENEZUELA',
        'VIETNAM',
        'WALLIS &amp; FUTUNA',
        'YEMEN',
        'YOUGOSLAVIE',
        'ZAMBIE',
        'ZIMBABWE',
        'ZONE NEUTRE IRK/SAU',
    ];

    $nationalities = [
        "Afghanne",
        "Sud-africaine",
        "Albanienne",
        "Algérienne",
        "Allemande",
        "Andorran",
        "Angolaise",
        "ANGUILLAN",
        "Antarticque",
        "ANTIGUAN",
        "Neerlandaise",
        "Saoudienne",
        "Argentine",
        "Arménienne",
        "Australienne",
        "PALESTINIEN",
        "Autrichienne",
        "AZERI",
        "BAHAMIEN",
        "Bahrani",
        "Bangladeshi",
        "Barbadien",
        "BIELORUSSE",
        "Belge",
        "BELIZEEN",
        "Béninoise",
        "Britannique Bermudes",
        "BHOUTANIEN",
        "Bolivienne",
        "Bosniaque",
        "BOTSOWANIEN",
        "Brésilienne",
        "Bruneien",
        "Bulgare",
        "Burkinabé",
        "Burundaise",
        "CAMBODGIEN",
        "Camérounaise",
        "Canadienne",
        "Cap Verdienne",
        "Chilienne",
        "Chinoise",
        "Chipriote",
        "Colombienne",
        "Comorienne",
        "Congolaise",
        "NORD COREEN",
        "Sud-coréenne",
        "COSTA RICAIN",
        "Croate",
        "Cubaine",
        "Danoise",
        "Djiboutienne",
        "Dominicaine",
        "Egyptienne",
        "SALVADORIEN",
        "Arabe des emirats",
        "Equatorienne",
        "Erythréenne",
        "Espagnole",
        "Estonienne",
        "Ethiopienne",
        "BRITANIQUE FALKLAND",
        "Fidjienne",
        "Finlandaise",
        "Française",
        "Togolaise",
        "Gambienne",
        "Georgienne",
        "Sud georgienne",
        "Ghanéenne",
        "BRITANIQUE GIBRALTAR",
        "Grecque",
        "Grenadan",
        "Guadeloopeenne",
        "AMERICAIN GUAM",
        "GUATEMALTEQUE",
        "Guinéenne",
        "Bissao-guinéenne",
        "Equatoguinéenne",
        "Guyanaise",
        "Haïtienne",
        "HONDURIEN",
        "CHINOIS DE HONG KONG",
        "HONGROIS",
        "NORVEGIEN",
        "AUSTRALIEN CHRISTMAS",
        "AUSTRALIEN NORFOLK",
        "BRITANIQUE CAYMAN",
        "Austalienne",
        "COOK",
        "AMERICAIN MARSHALL",
        "NEO ZELANDAIS",
        "AMERICAIN PACIFIC US",
        "AMERICAIN ILES VIERGE",
        "BRITANIQUE ILES VIERGE",
        "Indienne",
        "Indonésienne",
        "Irakienne",
        "Iranienne",
        "Irlandaise",
        "Islandaise",
        "Israélienne",
        "Italienne",
        "Jamaïcaine",
        "Japonaise",
        "Jordanienne",
        "KASAKH",
        "KENYAN",
        "KIRGHISTANAIS",
        "KIRIBATIEN",
        "KOWEITIEN",
        "LAOTIEN",
        "LESOTHONIEN",
        "LETTON",
        "Libanaise",
        "Libérienne",
        "Lybienne",
        "LIECHTENSTEINAIS",
        "Lithuanienne",
        "Luxembourgeoise",
        "CHINOIS DE MACAO",
        "MACEDONIEN",
        "Malgache",
        "Malawienne",
        "Malaisienne",
        "MALDIVAIS",
        "Malienne",
        "MALTAIS",
        "AMERICAIN MARIANE NORD",
        "Marocaine",
        "MARTINIQUAIS",
        "Mauricienne",
        "Mautiritanienne",
        "FRANCAIS MAYOTTE",
        "Méxicaine",
        "AMERICAIN MICRONESIE",
        "MOLDAVE",
        "MONEGASQUE",
        "MONGOL",
        "MONTSERRATIEN",
        "Mozambiquaise",
        "BIRMAN",
        "Namibienne",
        "NAURUEN",
        "Nepalaise",
        "NICARAGUAIEN",
        "Nigérienne",
        "Nigériane",
        "NEO ZELANDAIS NIUE",
        "Norvegienne",
        "Caledonienne",
        "OMANI",
        "Ougandaise",
        "OUZBEK",
        "Pakistanaise",
        "PALAUAN",
        "PANAMEEN",
        "PAPOU",
        "PARAGUAYEN",
        "PAYS ETRANGER",
        "PERUVIEN",
        "PHILIPPIN",
        "BRITANIQUE PITCAIRN",
        "Polonaise",
        "FRANCAIS POLYNESIE",
        "AMERICAIN PORTO RICO",
        "Portugais",
        "QUATARI",
        "Congolaise RDC",
        "Centrafricaine",
        "DOMINICAIN REP.",
        "Tchèque",
        "REUNIONAIS",
        "Roumaine",
        "Britanique",
        "Russe",
        "Rwandaise",
        "SAHRAWI",
        "SAN MARINAIS",
        "BRITANIQUE STE HELENE",
        "SOLOMON",
        "SAMOAN",
        "Américain SAMOA",
        "SAO TOMIEN",
        "Sénégalaise",
        "SEYCHELLOIS",
        "SIERRA LEONAIS",
        "SINGAPOURIEN",
        "SLOVAQUE",
        "SLOVENE",
        "Somalienne",
        "Soudanaise",
        "SRI LANKAIS",
        "ST KITTS",
        "VINCENTAIS",
        "FRANCAIS ST PIERRE MIQ.",
        "SAINT LUCIEN",
        "SUEDOIS",
        "Suisse",
        "SURINAMIEN",
        "NORVEGIEN SVALBARD",
        "SWAZILANDAIS",
        "SYRIEN",
        "FRANCAIS TAAF",
        "TADJIK",
        "CHINOIS DE TAIWAN",
        "TANZANIEN",
        "Tchadienne",
        "BRITANIQUE TBOI",
        "THAILANDAIS",
        "INDONESIEN",
        "TONGIEN",
        "TRINIDADIEN",
        "Tunisienne",
        "BRITANIQUE TURK ET CAIQUE",
        "TURKMENE",
        "Turque",
        "TUVALIEN",
        "Ukrainienne",
        "EUROPEEN",
        "URUGUAYEN",
        "Américaine",
        "NIVANUATU",
        "VATICAN",
        "VENEZUELIEN",
        "VIETNAMIEN",
        "FRANCAIS WALLIS FUTUN",
        "YEMENITE",
        "Yougoslave",
        "Zaïroise",
        "Zimbabweenne",
        "ZONE NEUTRE",


    ]
@endphp

<x-layout.partials.select name="nationalite" placeholder="Nationalité" :options="$nationalities" label="Nationalité" required="true" />


    
   